### ISSUE TITLE
Nutanix update OS

### ISSUE THREAD

**Issue by dcantos** [aldevar/Zabbix_Nutanix_Template#4]
have the following problem with the template, update the latest version of the nutanix OS and now it gives me this error in the zabbix-server log:
114405:20200106:150754.108 item "Prisma_NTX:dstNumFreePercent[1]" became not supported: Cannot evaluate expression: "Cannot evaluate function "last()": not enough data.".
114404:20200106:150755.127 item "Prisma_NTX:dstNumFreePercent[2]" became not supported: Cannot evaluate expression: "Cannot evaluate function "last()": not enough data.".
114405:20200106:150756.144 item "Prisma_NTX:dstNumFreePercent[3]" became not supported: Cannot evaluate expression: "Cannot evaluate function "last()": not enough data.".
114402:20200106:150757.156 item "Prisma_NTX:dstNumFreePercent[4]" became not supported: Cannot evaluate expression: "Cannot evaluate function "last()": not enough data.".
114402:20200106:150757.156 item "Prisma_NTX:dstNumFreePercent[5]" became not supported: Cannot evaluate expression: "Cannot evaluate function "last()": not enough data.".
114404:20200106:150758.166 item "Prisma_NTX:dstNumFreePercent[6]" became not supported: Cannot evaluate expression: "Cannot evaluate function "last()": not enough data.".
114402:20200106:150759.216 item "Prisma_NTX:dstNumFreePercent[7]" became not supported: Cannot evaluate expression: "Cannot evaluate function "last()": not enough data.".
114402:20200106:150800.249 item "Prisma_NTX:dstNumFreePercent[8]" became not supported: Cannot evaluate expression: "Cannot evaluate function "last()": not enough data.".
114405:20200106:150802.188 item "Prisma_NTX:dstNumFreePercent[9]" became not supported: Cannot eval

and it doesn't connect the SNMP, I don't have data to monitor, can you help me please.

**Comment by dcantos** [comment]
![zabbix_error](https://user-images.githubusercontent.com/6325635/71829169-fb133880-3071-11ea-933c-3c488b3cbb13.png)

**Comment by aldevar** [comment]
Hi, 
It seems your SNMP configuration is not correct.
When you point your mouse to the red SNMP symbol, what does it tell you?

**Comment by dcantos** [comment]
thanks and solutions by changing the MIB of the current version and restart the service.

but the following errors appear:
142795:20200106:105805.096 item "Nutanix:cstMetadataServiceStatus[51fb6ff0-707c-4b89-80a4-f34866f3e0fe.]" became not supported: snmp_parse_oid(): cannot parse OID "cstMetadataServiceStatus.2".

118476:20200106:155922.898 item "Prisma_NTX:citAvgLatencyUsecs[NutanixManagementShare.]" became not supported: snmp_parse_oid(): cannot parse OID "citAvgLatencyUsecs.3".
118495:20200106:155951.742 cannot send list of active checks to "10.0.1.4": host [zabbix-01.teuno] not found
118475:20200106:160011.287 item "Prisma_NTX:dstNumTotalInodes[6]" became not supported: snmp_parse_oid(): cannot parse OID "dstNumTotalInodes.6".
118475:20200106:160011.287 item "Prisma_NTX:dstNumFreeBytes[7]" became not supported: snmp_parse_oid(): cannot parse OID "dstNumFreeBytes.7".
118475:20200106:160011.287 item "Prisma_NTX:citTotalCapacity[default-container-53314264710429.]" became not supported: snmp_parse_oid(): cannot parse OID "citTotalCapacity.2".
118475:20200106:160011.287 item "Prisma_NTX:dstNumFreeInodes[9]" became not supported: snmp_parse_oid(): cannot parse OID "dstNumFreeInodes.9".
118475:20200106:160011.287 item "Prisma_NTX:dstNumFreeInodes[2]" became not supported: snmp_parse_oid(): cannot parse OID "dstNumFreeInodes.2".
118475:20200106:160011.287 item "Prisma_NTX:citTotalCapacity[SelfServiceContainer.]" became not supported: snmp_parse_oid(): cannot parse OID "citTotalCapacity.1".
118475:20200106:160011.287 item "Prisma_NTX:dstNumFreeInodes[3]" became not supported: snmp_parse_oid(): cannot parse OID "dstNumFreeInodes.3".
118475:20200106:160011.287 item "Prisma_NTX:dstNumFreeBytes[9]" became not supported: snmp_parse_oid(): cannot parse OID "dstNumFreeBytes.9".
118475:20200106:160011.287 item "Prisma_NTX:dstNumFreeBytes[8]" became not supported: snmp_parse_oid(): cannot parse OID "dstNumFreeBytes.8".
118475:20200106:160011.287 item "Prisma_NTX:dstNumTotalBytes[3]" became not supported: snmp_parse_oid(): cannot parse OID "dstNumTotalBytes.3".
118475:20200106:160011.287 item "Prisma_NTX:dstNumFreeInodes[4]" became not supported: snmp_parse_oid(): cannot parse OID "dstNumFreeInodes.4".
118475:20200106:160011.287 item "Prisma_NTX:dstNumFreeInodes[5]" became not supported: snmp_parse_oid(): cannot parse OID "dstNumFreeInodes.5".
118475:20200106:160011.287 item "Prisma_NTX:dstNumTotalBytes[1]" became not supported: snmp_parse_oid(): cannot parse OID "dstNumTotalBytes.1".
118475:20200106:160011.287 item "Prisma_NTX:dstNumTotalBytes[2]" became not supported: snmp_parse_oid(): cannot parse OID "dstNumTotalBytes.2".
118475:20200106:160011.287 item "Prisma_NTX:dstNumFreeInodes[7]" became not supported: snmp_parse_oid(): cannot parse OID "dstNumFreeInodes.7".
118475:20200106:160011.287 item "Prisma_NTX:citUsedCapacity[NutanixManagementShare.]" became not supported: snmp_parse_oid(): cannot parse OID "citUsedCapacity.3".
118475:20200106:160011.287 item "Prisma_NTX:dstNumFreeInodes[1]" became not supported: snmp_parse_oid(): cannot parse OID "dstNumFreeInodes.1".
118475:20200106:160011.287 item "Prisma_NTX:citTotalCapacity[NutanixManagementShare.]" became not supported: snmp_parse_oid(): cannot parse OID "citTotalCapacity.3".
118475:20200106:160011.287 item "Prisma_NTX:citUsedCapacity[SelfServiceContainer.]" became not supported: snmp_parse_oid(): cannot parse OID "citUsedCapacity.1".
118475:20200106:160011.287 item "Prisma_NTX:dstNumFreeBytes[5]" became not supported: snmp_parse_oid(): cannot parse OID "dstNumFreeBytes.5".
118475:20200106:160011.287 item "Prisma_NTX:citIOPerSecond[default-container-53314264710429.]" became not supported: snmp_parse_oid(): cannot parse OID "citIOPerSecond.2".
118475:20200106:160011.288 item "Prisma_NTX:dstDiskId[3]" became not supported: snmp_parse_oid(): cannot parse OID "dstDiskId.3".
118475:20200106:160011.288 item "Prisma_NTX:dstNumTotalInodes[2]" became not supported: snmp_parse_oid(): cannot parse OID "dstNumTotalInodes.2".
118475:20200106:160011.288 item "Prisma_NTX:dstDiskId[9]" became not supported: snmp_parse_oid(): cannot parse OID "dstDiskId.9".
118475:20200106:160011.288 item "Prisma_NTX:citIOPerSecond[NutanixManagementShare.]" became not supported: snmp_parse_oid(): cannot parse OID "citIOPerSecond.3".
118475:20200106:160011.288 item "Prisma_NTX:dstNumFreeBytes[4]" became not supported: snmp_parse_oid(): cannot parse OID "dstNumFreeBytes.4".

**Comment by aldevar** [comment]
Did you restart Zabbix process after uploading the MIB on the server?
Can you try a snmpget or snmpwalk from commandline?
Also, can you answer my previous question?

**Comment by dcantos** [comment]
1. yes
2. if i have results
3. it's already in green

**Comment by dcantos** [comment]
118476:20200106:171611.909 item "Prisma_NTX:clusterIops" became not supported: snmp_parse_oid(): cannot parse OID "clusterIops.0".
118476:20200106:171611.909 item "Prisma_NTX:cstControllerVMStatus[d5c8549b-6310-42f7-b2cd-9e6d62b5d8ea.]" became not supported: snmp_parse_oid(): cannot parse OID "cstControllerVMStatus.1".
118476:20200106:171611.909 item "Prisma_NTX:cstMetadataServiceStatus[51fb6ff0-707c-4b89-80a4-f34866f3e0fe.]" became not supported: snmp_parse_oid(): cannot parse OID "cstMetadataServiceStatus.2".
118476:20200106:171611.909 item "Prisma_NTX:cstMetadataServiceStatus[d5c8549b-6310-42f7-b2cd-9e6d62b5d8ea.]" became not supported: snmp_parse_oid(): cannot parse OID "cstMetadataServiceStatus.1".

**Comment by aldevar** [comment]
It seems your MIB file is not loaded by Zabbix.
Can you try this command from Zabbix server : 
`snmpwalk -v 3 -u YOURUSER -a SHA -A YOURAUTH -x AES -X YOURPASS -l authPriv IP.OF.PRISM hypervisorName -m NUTANIX-MIB`

It should return the list of your Nutanix hypervisors.
